### ISSUE TITLE
set up on local host?

### ISSUE THREAD

**Issue by anonsecbotnetstudent123** [i-am-unbekannt/AXIS#3]
i have ask many people but they don't know the answer. May be set up use ngrok or playit

**Comment by i-am-unbekannt** [comment]
Hello anonsecbotnetstudent123,

I am not aware of any way to run this through ngrok or playit. However, you could set up the botnet locally. To do this, you would need to set up the botnet on a computer at your home and open the ports on your router for the botnet. Since this method is quite cumbersome and insecure, I recommend using Linode instead. You can create a VM with 2 CPUs, 4GB RAM, and 80GB storage for only $20 per month.

~ Unbekannt
